### ISSUE TITLE
Серые(Grey)

### ISSUE THREAD

**Issue by kirillwars** [AndyAdjutor/SovietStation-VG#1]
ВаГинщики ленивые и не потрудились написать о них в вики, почему только общение на расстоянии?Они же телепатики. Не добавишь ли им телепатию и умение видеть глазами других, что собственно относится к телепатии на прямую. Добавлено: Поправка, телекинез и видеть глазами других.

**Comment by AndyAdjutor** [comment]
Кирилл, по беку они только телепаты. И не надо им ништяков сверх меры, тем более у них нет никаких недостатков для такого количества преимуществ.
